[package]
name = "wna"
version = "0.2.0"
authors = ["Yakov Bakhmatov <yakov@bakhmatov.ru>"]
description = "Windows Notification Area"
edition = "2018"
license = "MIT"

[dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "libloaderapi", "shellapi", "winuser"] }
